cat <<EOF > $HOME/.gitconfig
# This gitconfig was generated by attiand-zsh

[user]
  name = $ATTIAND_ZSH_NAME
  email = $ATTIAND_ZSH_EMAIL

[pull]
  ff = only

[push]
  default = simple

[color]
  ui = true

[alias]
  s = status
  st = status --short
  co = checkout
  br = branch
  last = log -1 --stat
  lg = log --all --graph --pretty='%h %C(cyan)%cd %C(auto)%d %C(bold yellow)%an%n%C(reset)%<(139,trunc)%s%n'

[log]
  date = format:'%Y-%m-%d %H:%M'

[merge]
  tool = code
  conflictstyle = diff3

[diff]
  tool = code

[difftool]
  prompt = false

[difftool "code"]
  cmd = code --wait --diff \$LOCAL \$REMOTE

[mergetool "code"]
  cmd = code --wait --merge \$REMOTE \$LOCAL \$BASE \$MERGED

[difftool "meld"]
  cmd = meld \$LOCAL \$REMOTE

[mergetool "meld"]
  cmd = meld \$LOCAL \$BASE \$REMOTE -o \$MERGED --diff \$BASE \$LOCAL --diff \$BASE \$REMOTE --auto-merge

EOF
