mkdir -p $HOME/.config/helix

FILE=$HOME/.config/helix/config.toml

if [ ! -f $FILE ]; then
	cat <<-EOF > $FILE
	# This file was generated by attiand-zsh
	theme = "nord-night"

	[editor]
	cursorline = true
	lsp.display-inlay-hints = true
EOF
fi
