mkdir -p "${HOME}/.config/helix/themes"

CONFIG_FILE=${HOME}/.config/helix/config.toml

if [ ! -f $CONFIG_FILE ]; then
	cat <<-EOF > $CONFIG_FILE
	# This file was generated by attiand-zsh
	theme = "attiand"

	[editor]
	cursorline = true
	color-modes = true

	[editor.file-picker]
	hidden = false

	[editor.statusline]
	left = ["mode", "spacer", "version-control", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
	right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

EOF
fi

ATTIAND_THEME=${HOME}/.config/helix/themes/attiand.toml

if [ ! -f $ATTIAND_THEME ]; then
	cat <<-EOF > $ATTIAND_THEME

	# This file was generated by attiand-zsh

	inherits = "catppuccin_mocha"

	"ui.statusline.normal" = { fg = "base", bg = "red", modifiers = ["bold"] }

EOF
fi
