mkdir -p "${HOME}/.config/ghostty"

CONFIG_FILE=${HOME}/.config/ghostty/config

if [ ! -f $CONFIG_FILE ]; then
        cat <<-EOF > $CONFIG_FILE
        # This file was generated by attiand-zsh
        config-file = $BASEDIR/etc/ghostty/config
EOF
fi